export const getBoneList = () => ([
  ["axial", "skull", "cranial bone", "frontal"],
  ["axial", "skull", "cranial bone", "occipital"],
  ["axial", "skull", "cranial bone", "sphenoid"],
  ["axial", "skull", "cranial bone", "ethmoid"],
  ["axial", "skull", "cranial bone", "parietal"],
  ["axial", "skull", "cranial bone", "temporal"],
  ["axial", "skull", "facial bones", "mandible"],
  ["axial", "skull", "facial bones", "vomer"],
  ["axial", "skull", "facial bones", "maxilla"],
  ["axial", "skull", "facial bones", "zygomatic"],
  ["axial", "skull", "facial bones", "lacrimal"],
  ["axial", "skull", "facial bones", "nasal"],
  ["axial", "skull", "facial bones", "palatine"],
  ["axial", "skull", "facial bones", "nasal concha"],
  ["axial", "skull", "sutures", "coronal"],
  ["axial", "skull", "sutures", "sagittal"],
  ["axial", "skull", "sutures", "squamous"],
  ["axial", "skull", "sutures", "lambdoid"],
  ["axial", "skull", "processes", "styloid process (part of temporal bone)"],
  ["axial", "skull", "processes", "zygomatic process (part of temporal bone)"],
  ["axial", "skull", "processes", "mastoid process (part of temporal bone)"],
  ["axial", "skull", "processes", "palatine process (part of the maxilla", "abuts the palatine bone)"],
  ["axial", "skull", "processes", "coronoid process (part of the mandible)"],
  ["axial", "skull", "processes", "condylar process (part of mandible)"],
  ["axial", "skull", "foramins", "foramen magnum"],
  ["axial", "skull", "foramins", "supraorbital foramen (notch)"],
  ["axial", "skull", "foramins", "infraorbital foramen"],
  ["axial", "skull", "foramins", "mental foramen"],
  ["axial", "skull", "foramins", "optic canals"],
  ["axial", "skull", "foramins", "foramen ovale"],
  ["axial", "skull", "foramins", "carotid canal"],
  ["axial", "skull", "foramins", "jugular foramen"],
  ["axial", "skull", "other structures", "occipital condyles"],
  ["axial", "skull", "other structures", "zygomatic arch"],
  ["axial", "skull", "other structures", "orbit (the bony eye socket)"],
  ["axial", "skull", "other structures", "sella turcica"],
  ["axial", "skull", "other structures", "crista galli"],
  ["axial", "skull", "other structures", "cribiform plates"],
  ["axial", "skull", "other structures", "external acoustic meatus"],
  ["axial", "skull", "other structures", "hard palate (the palatine process of the maxilla and the palatine bones, together)"],
  ["axial", "skull", "ear ossicles", "malleus"],
  ["axial", "skull", "ear ossicles", "incus"],
  ["axial", "skull", "ear ossicles", "stapes"],
  ["axial", "vertebral column", "types", "cervical"],
  ["axial", "vertebral column", "types", "atlas (C1)"],
  ["axial", "vertebral column", "types", "axis (C2)"],
  ["axial", "vertebral column", "types", "thoracic"],
  ["axial", "vertebral column", "types", "lumbar"],
  ["axial", "vertebral column", "types", "sacral"],
  ["axial", "vertebral column", "types", "coccyx"],
  ["axial", "vertebral column", "parts", "body"],
  ["axial", "vertebral column", "parts", "spinous process"],
  ["axial", "vertebral column", "parts", "transverse process"],
  ["axial", "vertebral column", "parts", "transverse foramen"],
  ["axial", "vertebral column", "parts", "articular processes (there are inferior and superior)"],
  ["axial", "vertebral column", "parts", "vertebral foramen"],
  ["axial", "vertebral column", "parts", "costal facets"],
  ["axial", "vertebral column", "parts", "dens"],
  ["axial", "thorax", "parts of a rib", "head"],
  ["axial", "thorax", "parts of a rib", "neck"],
  ["axial", "thorax", "parts of a rib", "tubercle"],
  ["axial", "thorax", "parts of a sternum", "sternum"],
  ["axial", "thorax", "parts of a sternum", "manubrium"],
  ["axial", "thorax", "parts of a sternum", "body"],
  ["axial", "thorax", "parts of a sternum", "xiphoid process"],
  ["axial", "thorax", "parts of a sternum", "clavicular notch"],
  ["axial", "thorax", "parts of a sternum", "jugular notch"],
  ["axial", "hyoid bone", "hyoid bone", "hyoid bone"],
  ["appendicular", "shoulder girdle", "parts of the scapula", "scapula"],
  ["appendicular", "shoulder girdle", "parts of the scapula", "spine"],
  ["appendicular", "shoulder girdle", "parts of the scapula", "acromion"],
  ["appendicular", "shoulder girdle", "parts of the scapula", "glenoid fossa"],
  ["appendicular", "shoulder girdle", "parts of the scapula", "supraspinous fossa"],
  ["appendicular", "shoulder girdle", "parts of the scapula", "infraspinous fossa"],
  ["appendicular", "shoulder girdle", "parts of the scapula", "subscapular fossa"],
  ["appendicular", "shoulder girdle", "parts of the scapula", "coracoid process"],
  ["appendicular", "shoulder girdle", "parts of the clavicle", "clavicle"],
  ["appendicular", "shoulder girdle", "parts of the clavicle", "sternal end"],
  ["appendicular", "shoulder girdle", "parts of the clavicle", "acromial end"],
  ["appendicular", "upper appengages", "parts of the humerus", "humerus"],
  ["appendicular", "upper appengages", "parts of the humerus", "head"],
  ["appendicular", "upper appengages", "parts of the humerus", "surgical neck"],
  ["appendicular", "upper appengages", "parts of the humerus", "greater tubercle"],
  ["appendicular", "upper appengages", "parts of the humerus", "lesser tubercle"],
  ["appendicular", "upper appengages", "parts of the humerus", "lateral epicondyle"],
  ["appendicular", "upper appengages", "parts of the humerus", "medial epicondyle"],
  ["appendicular", "upper appengages", "parts of the humerus", "trochlea"],
  ["appendicular", "upper appengages", "parts of the humerus", "capitulum"],
  ["appendicular", "upper appengages", "parts of the humerus", "coronoid fossa"],
  ["appendicular", "upper appengages", "parts of the humerus", "olecranon fossa"],
  ["appendicular", "upper appengages", "parts of the humerus", "deltoid tuberosity"],
  ["appendicular", "upper appengages", "parts of the ulna", "ulna"],
  ["appendicular", "upper appengages", "parts of the ulna", "olecranon process"],
  ["appendicular", "upper appengages", "parts of the ulna", "coronoid process"],
  ["appendicular", "upper appengages", "parts of the ulna", "trochlear notch"],
  ["appendicular", "upper appengages", "parts of the ulna", "radial notch"],
  ["appendicular", "upper appengages", "parts of the ulna", "styloid process"],
  ["appendicular", "upper appengages", "parts of the ulna", "head"],
  ["appendicular", "upper appengages", "parts of the radius", "radius"],
  ["appendicular", "upper appengages", "parts of the radius", "head"],
  ["appendicular", "upper appengages", "parts of the radius", "neck"],
  ["appendicular", "upper appengages", "parts of the radius", "radial tuberosity"],
  ["appendicular", "upper appengages", "parts of the radius", "styloid process"],
  ["appendicular", "upper appengages", "parts of the radius", "ulnar notch"],
  ["appendicular", "upper appengages", "carpals", "scaphoid"],
  ["appendicular", "upper appengages", "carpals", "lunate"],
  ["appendicular", "upper appengages", "carpals", "triquetrum"],
  ["appendicular", "upper appengages", "carpals", "pisiform"],
  ["appendicular", "upper appengages", "carpals", "trapezium"],
  ["appendicular", "upper appengages", "carpals", "trapezoid"],
  ["appendicular", "upper appengages", "carpals", "capitate"],
  ["appendicular", "upper appengages", "carpals", "hamate"],
  ["appendicular", "upper appengages", "parts of the metacarpals", "base"],
  ["appendicular", "upper appengages", "parts of the metacarpals", "head"],
  ["appendicular", "upper appengages", "types of metacarpals", "phalanges I-V"],
  ["appendicular", "upper appengages", "parts of the phalanges", "proximal"],
  ["appendicular", "upper appengages", "parts of the phalanges", "middle"],
  ["appendicular", "upper appengages", "parts of the phalanges", "distal"],
  ["appendicular", "upper appengages", "parts of the phalanges", "pollex"],
  ["appendicular", "upper appengages", "types of phalanges", "phalanges I-V"],
  ["appendicular", "palvic (hip) girdle", "parts of the os coxae (hip bone)", "ilium"],
  ["appendicular", "palvic (hip) girdle", "parts of the os coxae (hip bone)", "ischium"],
  ["appendicular", "palvic (hip) girdle", "parts of the os coxae (hip bone)", "pubis"],
  ["appendicular", "palvic (hip) girdle", "parts of the os coxae (hip bone)", "iliac crest"],
  ["appendicular", "palvic (hip) girdle", "parts of the os coxae (hip bone)", "anterior superior iliac spine"],
  ["appendicular", "palvic (hip) girdle", "parts of the os coxae (hip bone)", "posterior superior iliac spine"],
  ["appendicular", "palvic (hip) girdle", "parts of the os coxae (hip bone)", "anterior inferior iliac spine"],
  ["appendicular", "palvic (hip) girdle", "parts of the os coxae (hip bone)", "posterior inferior iliac spine"],
  ["appendicular", "palvic (hip) girdle", "parts of the os coxae (hip bone)", "greater sciatic notch"],
  ["appendicular", "palvic (hip) girdle", "parts of the os coxae (hip bone)", "ischial tuberosity"],
  ["appendicular", "palvic (hip) girdle", "parts of the os coxae (hip bone)", "lesser sciatic notch"],
  ["appendicular", "palvic (hip) girdle", "parts of the os coxae (hip bone)", "acetabulum"],
  ["appendicular", "palvic (hip) girdle", "parts of the os coxae (hip bone)", "obturator foramen"],
  ["appendicular", "palvic (hip) girdle", "parts of the os coxae (hip bone)", "pubic symphysis"],
  ["appendicular", "palvic (hip) girdle", "parts of the os coxae (hip bone)", "sacroiliac joint (evidence of)"],
  ["appendicular", "lower appendages", "parts of the femur", "femur"],
  ["appendicular", "lower appendages", "parts of the femur", "head"],
  ["appendicular", "lower appendages", "parts of the femur", "neck"],
  ["appendicular", "lower appendages", "parts of the femur", "greater trochanter"],
  ["appendicular", "lower appendages", "parts of the femur", "lesser trochanter"],
  ["appendicular", "lower appendages", "parts of the femur", "lateral epicondyle"],
  ["appendicular", "lower appendages", "parts of the femur", "medial epicondyle"],
  ["appendicular", "lower appendages", "parts of the femur", "lateral condyle"],
  ["appendicular", "lower appendages", "parts of the femur", "medial condyle"],
  ["appendicular", "lower appendages", "parts of the femur", "intercondylar fossa"],
  ["appendicular", "lower appendages", "parts of the femur", "patellar surface"],
  ["appendicular", "lower appendages", "parts of the patella", "patella"],
  ["appendicular", "lower appendages", "parts of the patella", "base"],
  ["appendicular", "lower appendages", "parts of the patella", "apex"],
  ["appendicular", "lower appendages", "parts of the patella", "articular facets"],
  ["appendicular", "lower appendages", "parts of the tibia", "tibia"],
  ["appendicular", "lower appendages", "parts of the tibia", "lateral condyle"],
  ["appendicular", "lower appendages", "parts of the tibia", "medial condyle"],
  ["appendicular", "lower appendages", "parts of the tibia", "tibial tuberosity"],
  ["appendicular", "lower appendages", "parts of the tibia", "intercondylar eminence"],
  ["appendicular", "lower appendages", "parts of the tibia", "medial malleolus"],
  ["appendicular", "lower appendages", "parts of the fibula", "fibula"],
  ["appendicular", "lower appendages", "parts of the fibula", "head"],
  ["appendicular", "lower appendages", "parts of the fibula", "neck"],
  ["appendicular", "lower appendages", "parts of the fibula", "lateral malleolus"],
  ["appendicular", "lower appendages", "types of tarsals", "calcaneus"],
  ["appendicular", "lower appendages", "types of tarsals", "talus"],
  ["appendicular", "lower appendages", "types of tarsals", "cuboid"],
  ["appendicular", "lower appendages", "types of tarsals", "navicular"],
  ["appendicular", "lower appendages", "types of tarsals", "lateral cuneiform"],
  ["appendicular", "lower appendages", "types of tarsals", "intermediate cuneiform"],
  ["appendicular", "lower appendages", "types of tarsals", "medial cuneiform"],
  ["appendicular", "lower appendages", "metatarsals", "I-V"],
  ["appendicular", "lower appendages", "types and parts of the phalenges", "phalenges"],
  ["appendicular", "lower appendages", "types and parts of the phalenges", "proximal"],
  ["appendicular", "lower appendages", "types and parts of the phalenges", "middle"],
  ["appendicular", "lower appendages", "types and parts of the phalenges", "distal"],
  ["appendicular", "lower appendages", "types and parts of the phalenges", "hallux"],
]);
